AWSTemplateFormatVersion: 2010-09-09
Description: A Cloud Formation Template to Create A Load Balancer for ECS Cluster.
Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
  ContainerPort:
    Type: Number
    Default: 8080
  LoadBalancerPort:
    Type: Number
    Default: 80
  LoadBalancerhttpsPort:
    Type: Number
    Default: 443
  ApplicationCI:
    Type: String
    Description: Lowercase ApplicationCI Example abc
    Default: saf
  MaintenanceWindow:
    Default: Tue:04:00-Tue:04:30
    Type: String
  SLALevel:
    Default: 3
    Type: String
  RiskDataClass:
    Default: Moderate:Confidential
    Type: String
  ApplicationContactDL:
    Default: safwanmodak30@gmail.com
    Type: String
  InternalExternal:
    Default: Internal
    Type: String
  LoadBalancerCertificateArn:
    Type: String
  RegulatoryControls:
    Default: PII
    Type: String
  AppEnv:
    Type: String
  DataRetentionPeriod:
    Type: String
    Default: 5 years
  DnsName:
    Type: String
  RoutePrefix:
    Type: String
    Default: test
  RouteName:
    Type: String
  RouteWeight:
    Type: Number

Resources:
  safLoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub ${ApplicationCI}-InternalLoadBalancerSecurityGroup
      GroupName: !Sub ${ApplicationCI}-InternalLoadBalancerSecurityGroup
      VpcId: !Ref VPC
      Tags:
        - Key: ApplicationCI
          Value: !Ref ApplicationCI
        - Key: SLALevel
          Value: !Ref SLALevel
        - Key: RiskDataClass
          Value: !Ref RiskDataClass
        - Key: ApplicationContactDL
          Value: !Ref ApplicationContactDL
        - Key: MaintenanceWindow
          Value: !Ref MaintenanceWindow
        - Key: InternalExternal
          Value: !Ref InternalExternal
        - Key: Name
          Value: !Sub ${ApplicationCI}-InternalLoadBalancerSecurityGroup
        - Key: RegulatoryControls
          Value: !Ref RegulatoryControls
        - Key: DataRetentionPeriod
          Value: !Ref DataRetentionPeriod

      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref LoadBalancerPort
          ToPort: !Ref LoadBalancerPort
          CidrIp: 100.64.0.0/16
        - IpProtocol: tcp
          FromPort: !Ref LoadBalancerhttpsPort
          ToPort: !Ref LoadBalancerhttpsPort
          CidrIp: 100.64.0.0/16
        - IpProtocol: tcp
          FromPort: !Ref LoadBalancerPort
          ToPort: !Ref LoadBalancerPort
          CidrIp: 10.0.0.0/8
        - IpProtocol: tcp
          FromPort: !Ref LoadBalancerhttpsPort
          ToPort: !Ref LoadBalancerhttpsPort
          CidrIp: 10.0.0.0/8
        - IpProtocol: tcp
          FromPort: !Ref LoadBalancerPort
          ToPort: !Ref LoadBalancerPort
          CidrIp: 57.23.242.64/26
        - IpProtocol: tcp
          FromPort: !Ref LoadBalancerhttpsPort
          ToPort: !Ref LoadBalancerhttpsPort
          CidrIp: 57.23.242.64/26
        - IpProtocol: tcp
          FromPort: !Ref LoadBalancerPort
          ToPort: !Ref LoadBalancerPort
          CidrIp: 57.23.131.0/27
        - IpProtocol: tcp
          FromPort: !Ref LoadBalancerhttpsPort
          ToPort: !Ref LoadBalancerhttpsPort
          CidrIp: 57.23.131.0/27
      SecurityGroupEgress:
        - IpProtocol: '-1'
          CidrIp: 0.0.0.0/0
  safLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '300'
        - Key: deletion_protection.enabled
          Value: true
        - Key: routing.http.drop_invalid_header_fields.enabled
          Value: 'true'
        - Key: routing.http.preserve_host_header.enabled
          Value: 'true'
      Name: !Sub ${ApplicationCI}-InternalLoadBalancer
      Tags:
        - Key: ApplicationCI
          Value: !Ref ApplicationCI
        - Key: SLALevel
          Value: !Ref SLALevel
        - Key: RiskDataClass
          Value: !Ref RiskDataClass
        - Key: ApplicationContactDL
          Value: !Ref ApplicationContactDL
        - Key: MaintenanceWindow
          Value: !Ref MaintenanceWindow
        - Key: InternalExternal
          Value: !Ref InternalExternal
        - Key: Name
          Value: !Sub ${ApplicationCI}-InternalLoadBalancer
        - Key: RegulatoryControls
          Value: !Ref RegulatoryControls
        - Key: Dns
          Value: !Ref DnsName

      Scheme: internal
      SecurityGroups:
        - !Ref safLoadBalancerSecurityGroup
      Subnets: !Ref Subnets

  safListenerHTTPS:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates:
        - CertificateArn: !Ref LoadBalancerCertificateArn
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            ContentType: text/plain
            MessageBody: Accepted
            StatusCode: "200"
      LoadBalancerArn: !Ref safLoadBalancer
      Port: !Ref LoadBalancerhttpsPort
      Protocol: HTTPS
      SslPolicy: "ELBSecurityPolicy-TLS-1-2-Ext-2018-06"

  safLoadBalancerArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: LoadBalancerArn
      Name: !Sub /${ApplicationCI}/elb/LoadBalancerURL
      Tags:
        ApplicationCI : !Ref ApplicationCI
      Tier: Standard
      Type: String
      Value: !GetAtt safLoadBalancer.DNSName

  safInternalLoadBalancerListenerHTTPSParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: InternalLoadBalancerListenerHTTPS
      Name: !Sub /${ApplicationCI}/elb/InternalLoadBalancerListenerHTTPS
      Tags:
        ApplicationCI : !Ref ApplicationCI
      Tier: Standard
      Type: String
      Value: !Ref safListenerHTTPS

  safInternalLoadBalancerSecurityGroupParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: safInternalLoadBalancerSecurityGroup
      Name: !Sub /${ApplicationCI}/ec2/InternalLoadBalancerSecurityGroup
      Tags:
        ApplicationCI : !Ref ApplicationCI
      Tier: Standard
      Type: String
      Value: !Ref safLoadBalancerSecurityGroup

  safHostedZone:
    Type: AWS::SSM::Parameter
    Properties:
      Description:  safHostedZone
      Name: !Sub /${ApplicationCI}/Route53/HostedZone
      Tags:
        ApplicationCI : !Ref ApplicationCI
      Tier: Standard
      Type: String
      Value: !GetAtt safLoadBalancer.CanonicalHostedZoneID


  ## route53 specific changes
  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub ${RoutePrefix}.${AppEnv}.${ApplicationCI}.aws.saf.com
      Type: A
      AliasTarget:
        DNSName: !GetAtt safLoadBalancer.DNSName
        HostedZoneId: !GetAtt safLoadBalancer.CanonicalHostedZoneID
      HostedZoneName: !Sub ${AppEnv}.${ApplicationCI}.aws.saf.com.
      Weight: !Ref RouteWeight
      SetIdentifier: !Ref AWS::Region

  DNSRecordRegionSpecific:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub ${RouteName}.${RoutePrefix}.${AppEnv}.${ApplicationCI}.aws.saf.com
      Type: CNAME
      TTL: '900'
      ResourceRecords:
        - !GetAtt safLoadBalancer.DNSName
      HostedZoneName: !Sub ${AppEnv}.${ApplicationCI}.aws.saf.com.

Outputs:
  safInternalLoadBalancerSecurityGroup:
    Description: LoadBalancerSecurityGroup
    Value: !Ref safLoadBalancerSecurityGroup
    Export:
      Name: !Sub ${ApplicationCI}-InternalLoadBalancerSecurityGroup
  safInternalLoadBalancer:
    Description: InternalLoadBalancer
    Value: !Ref safLoadBalancer
    Export:
      Name: !Sub ${ApplicationCI}-InternalLoadBalancer
  safInternalLoadBalancerUrl:
    Description: InternalLoadBalancerUrl
    Value: !GetAtt safLoadBalancer.DNSName
    Export:
      Name: !Sub ${ApplicationCI}-InternalLoadBalancerUrl
  safInternalLoadBalancerListenerHTTPS:
    Description: InternalLoadBalancerListener
    Value: !Ref safListenerHTTPS
    Export:
      Name: !Sub ${ApplicationCI}-InternalLoadBalancerListenerHTTPS